# coding: utf-8

"""
    GetHook API

    Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gethook.models.replay_event_data import ReplayEventData

class TestReplayEventData(unittest.TestCase):
    """ReplayEventData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ReplayEventData:
        """Test ReplayEventData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ReplayEventData`
        """
        model = ReplayEventData()
        if include_optional:
            return ReplayEventData(
                original_event_id = 'uuid',
                replay_event_id = 'uuid',
                status = 'queued'
            )
        else:
            return ReplayEventData(
                original_event_id = 'uuid',
                replay_event_id = 'uuid',
                status = 'queued',
        )
        """

    def testReplayEventData(self):
        """Test ReplayEventData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
