# coding: utf-8

"""
    GetHook API

    Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gethook.models.brand_settings import BrandSettings

class TestBrandSettings(unittest.TestCase):
    """BrandSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BrandSettings:
        """Test BrandSettings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BrandSettings`
        """
        model = BrandSettings()
        if include_optional:
            return BrandSettings(
                account_id = '',
                company_name = '',
                created_at = '',
                docs_title = '',
                id = '',
                logo_url = '',
                primary_color = '',
                support_email = '',
                updated_at = ''
            )
        else:
            return BrandSettings(
                account_id = '',
                created_at = '',
                id = '',
                updated_at = '',
        )
        """

    def testBrandSettings(self):
        """Test BrandSettings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
