# coding: utf-8

"""
    GetHook API

    Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gethook.models.stats_status_item import StatsStatusItem

class TestStatsStatusItem(unittest.TestCase):
    """StatsStatusItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatsStatusItem:
        """Test StatsStatusItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatsStatusItem`
        """
        model = StatsStatusItem()
        if include_optional:
            return StatsStatusItem(
                count = 35,
                status = 'delivered'
            )
        else:
            return StatsStatusItem(
                count = 35,
                status = 'delivered',
        )
        """

    def testStatsStatusItem(self):
        """Test StatsStatusItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
