# coding: utf-8

"""
    GetHook API

    Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gethook.models.direction import Direction

class TestDirection(unittest.TestCase):
    """Direction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDirection(self):
        """Test Direction"""
        # inst = Direction()

if __name__ == '__main__':
    unittest.main()
