# coding: utf-8

"""
    GetHook API

    Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gethook.models.destination_preset import DestinationPreset

class TestDestinationPreset(unittest.TestCase):
    """DestinationPreset unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DestinationPreset:
        """Test DestinationPreset
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DestinationPreset`
        """
        model = DestinationPreset()
        if include_optional:
            return DestinationPreset(
                auth_header = '',
                auth_label = '',
                auth_type = '',
                category = '',
                color = '',
                description = '',
                docs_url = '',
                extra_headers = {
                    'key' : ''
                    },
                id = '',
                name = '',
                url_hint = ''
            )
        else:
            return DestinationPreset(
        )
        """

    def testDestinationPreset(self):
        """Test DestinationPreset"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
