# coding: utf-8

"""
    GetHook API

    Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gethook.api.destinations_api import DestinationsApi


class TestDestinationsApi(unittest.TestCase):
    """DestinationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DestinationsApi()

    def tearDown(self) -> None:
        pass

    def test_create_destination(self) -> None:
        """Test case for create_destination

        Create destination
        """
        pass

    def test_get_destination(self) -> None:
        """Test case for get_destination

        Get destination
        """
        pass

    def test_list_destinations(self) -> None:
        """Test case for list_destinations

        List destinations
        """
        pass

    def test_update_destination(self) -> None:
        """Test case for update_destination

        Update destination
        """
        pass


if __name__ == '__main__':
    unittest.main()
