# coding: utf-8

"""
    GetHook API

    Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gethook.models.stats_daily_item import StatsDailyItem

class TestStatsDailyItem(unittest.TestCase):
    """StatsDailyItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StatsDailyItem:
        """Test StatsDailyItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StatsDailyItem`
        """
        model = StatsDailyItem()
        if include_optional:
            return StatsDailyItem(
                var_date = '2024-01-15',
                delivered = 35,
                failed = 3,
                inbound = 42,
                outbound = 38
            )
        else:
            return StatsDailyItem(
                var_date = '2024-01-15',
                delivered = 35,
                failed = 3,
                inbound = 42,
                outbound = 38,
        )
        """

    def testStatsDailyItem(self):
        """Test StatsDailyItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
