# coding: utf-8

"""
    GetHook API

    Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gethook.models.upsert_brand_settings_request import UpsertBrandSettingsRequest

class TestUpsertBrandSettingsRequest(unittest.TestCase):
    """UpsertBrandSettingsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpsertBrandSettingsRequest:
        """Test UpsertBrandSettingsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpsertBrandSettingsRequest`
        """
        model = UpsertBrandSettingsRequest()
        if include_optional:
            return UpsertBrandSettingsRequest(
                company_name = 'Acme Corp',
                docs_title = 'Acme Webhooks',
                logo_url = 'https://example.com/logo.png',
                primary_color = '#6366f1',
                support_email = 'support@example.com'
            )
        else:
            return UpsertBrandSettingsRequest(
        )
        """

    def testUpsertBrandSettingsRequest(self):
        """Test UpsertBrandSettingsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
