# coding: utf-8

"""
    GetHook API

    Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gethook.api.outbound_events_api import OutboundEventsApi


class TestOutboundEventsApi(unittest.TestCase):
    """OutboundEventsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OutboundEventsApi()

    def tearDown(self) -> None:
        pass

    def test_get_outbound_event(self) -> None:
        """Test case for get_outbound_event

        Get outbound event
        """
        pass

    def test_list_outbound_events(self) -> None:
        """Test case for list_outbound_events

        List outbound events
        """
        pass

    def test_publish_outbound_event(self) -> None:
        """Test case for publish_outbound_event

        Publish outbound event
        """
        pass

    def test_replay_outbound_event(self) -> None:
        """Test case for replay_outbound_event

        Replay outbound event
        """
        pass


if __name__ == '__main__':
    unittest.main()
