# coding: utf-8

"""
    GetHook API

    Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gethook.models.delivery_attempt import DeliveryAttempt

class TestDeliveryAttempt(unittest.TestCase):
    """DeliveryAttempt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeliveryAttempt:
        """Test DeliveryAttempt
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeliveryAttempt`
        """
        model = DeliveryAttempt()
        if include_optional:
            return DeliveryAttempt(
                attempt_number = 56,
                destination_id = '',
                error_message = '',
                event_id = '',
                finished_at = '',
                id = '',
                latency_ms = 56,
                outcome = 'pending',
                response_body = '',
                response_status = 56,
                started_at = ''
            )
        else:
            return DeliveryAttempt(
                attempt_number = 56,
                destination_id = '',
                event_id = '',
                id = '',
                outcome = 'pending',
                started_at = '',
        )
        """

    def testDeliveryAttempt(self):
        """Test DeliveryAttempt"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
