# coding: utf-8

"""
    GetHook API

    Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gethook.api.ingest_api import IngestApi


class TestIngestApi(unittest.TestCase):
    """IngestApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IngestApi()

    def tearDown(self) -> None:
        pass

    def test_ingest(self) -> None:
        """Test case for ingest

        Ingest webhook event
        """
        pass


if __name__ == '__main__':
    unittest.main()
