# coding: utf-8

"""
    GetHook API

    Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gethook.api.routes_api import RoutesApi


class TestRoutesApi(unittest.TestCase):
    """RoutesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RoutesApi()

    def tearDown(self) -> None:
        pass

    def test_create_route(self) -> None:
        """Test case for create_route

        Create route
        """
        pass

    def test_list_routes(self) -> None:
        """Test case for list_routes

        List routes
        """
        pass


if __name__ == '__main__':
    unittest.main()
