# coding: utf-8

"""
    GetHook API

    Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gethook.models.publish_outbound_event_request import PublishOutboundEventRequest

class TestPublishOutboundEventRequest(unittest.TestCase):
    """PublishOutboundEventRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublishOutboundEventRequest:
        """Test PublishOutboundEventRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublishOutboundEventRequest`
        """
        model = PublishOutboundEventRequest()
        if include_optional:
            return PublishOutboundEventRequest(
                event_type = 'order.created',
                external_event_id = 'evt_abc123',
                payload = '{"order_id":"123"}'
            )
        else:
            return PublishOutboundEventRequest(
                payload = '{"order_id":"123"}',
        )
        """

    def testPublishOutboundEventRequest(self):
        """Test PublishOutboundEventRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
