# coding: utf-8

"""
    GetHook API

    Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gethook.api.brand_api import BrandApi


class TestBrandApi(unittest.TestCase):
    """BrandApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BrandApi()

    def tearDown(self) -> None:
        pass

    def test_get_brand_settings(self) -> None:
        """Test case for get_brand_settings

        Get brand settings
        """
        pass

    def test_upsert_brand_settings(self) -> None:
        """Test case for upsert_brand_settings

        Upsert brand settings
        """
        pass


if __name__ == '__main__':
    unittest.main()
