# coding: utf-8

"""
    GetHook API

    Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gethook.models.attempt_outcome import AttemptOutcome

class TestAttemptOutcome(unittest.TestCase):
    """AttemptOutcome unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAttemptOutcome(self):
        """Test AttemptOutcome"""
        # inst = AttemptOutcome()

if __name__ == '__main__':
    unittest.main()
