# coding: utf-8

"""
    GetHook API

    Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gethook.models.create_route_request import CreateRouteRequest

class TestCreateRouteRequest(unittest.TestCase):
    """CreateRouteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateRouteRequest:
        """Test CreateRouteRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateRouteRequest`
        """
        model = CreateRouteRequest()
        if include_optional:
            return CreateRouteRequest(
                destination_id = 'uuid',
                event_type_pattern = 'order.*',
                source_id = 'uuid'
            )
        else:
            return CreateRouteRequest(
                destination_id = 'uuid',
        )
        """

    def testCreateRouteRequest(self):
        """Test CreateRouteRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
