# coding: utf-8

"""
    GetHook API

    Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gethook.api.sources_api import SourcesApi


class TestSourcesApi(unittest.TestCase):
    """SourcesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SourcesApi()

    def tearDown(self) -> None:
        pass

    def test_create_source(self) -> None:
        """Test case for create_source

        Create source
        """
        pass

    def test_get_source(self) -> None:
        """Test case for get_source

        Get source
        """
        pass

    def test_list_sources(self) -> None:
        """Test case for list_sources

        List sources
        """
        pass


if __name__ == '__main__':
    unittest.main()
