# coding: utf-8

"""
    GetHook API

    Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gethook.api.platform_api import PlatformApi


class TestPlatformApi(unittest.TestCase):
    """PlatformApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PlatformApi()

    def tearDown(self) -> None:
        pass

    def test_get_platform_stats(self) -> None:
        """Test case for get_platform_stats

        Public platform statistics
        """
        pass


if __name__ == '__main__':
    unittest.main()
