# coding: utf-8

"""
    GetHook API

    Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gethook.models.event_detail_data import EventDetailData

class TestEventDetailData(unittest.TestCase):
    """EventDetailData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EventDetailData:
        """Test EventDetailData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EventDetailData`
        """
        model = EventDetailData()
        if include_optional:
            return EventDetailData(
                attempts = [
                    gethook.models.delivery_attempt.DeliveryAttempt(
                        attempt_number = 56, 
                        destination_id = '', 
                        error_message = '', 
                        event_id = '', 
                        finished_at = '', 
                        id = '', 
                        latency_ms = 56, 
                        outcome = 'pending', 
                        response_body = '', 
                        response_status = 56, 
                        started_at = '', )
                    ],
                event = gethook.models.event.Event(
                    account_id = '', 
                    attempts_count = 56, 
                    body = '', 
                    created_at = '', 
                    created_by = '', 
                    direction = 'inbound', 
                    event_type = '', 
                    external_event_id = '', 
                    final_state = '', 
                    headers = { }, 
                    id = '', 
                    next_attempt_at = '', 
                    payload_hash = '', 
                    received_at = '', 
                    source_id = '', 
                    status = 'received', )
            )
        else:
            return EventDetailData(
                attempts = [
                    gethook.models.delivery_attempt.DeliveryAttempt(
                        attempt_number = 56, 
                        destination_id = '', 
                        error_message = '', 
                        event_id = '', 
                        finished_at = '', 
                        id = '', 
                        latency_ms = 56, 
                        outcome = 'pending', 
                        response_body = '', 
                        response_status = 56, 
                        started_at = '', )
                    ],
                event = gethook.models.event.Event(
                    account_id = '', 
                    attempts_count = 56, 
                    body = '', 
                    created_at = '', 
                    created_by = '', 
                    direction = 'inbound', 
                    event_type = '', 
                    external_event_id = '', 
                    final_state = '', 
                    headers = { }, 
                    id = '', 
                    next_attempt_at = '', 
                    payload_hash = '', 
                    received_at = '', 
                    source_id = '', 
                    status = 'received', ),
        )
        """

    def testEventDetailData(self):
        """Test EventDetailData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
