# coding: utf-8

"""
    GetHook API

    Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gethook.api.custom_domains_api import CustomDomainsApi


class TestCustomDomainsApi(unittest.TestCase):
    """CustomDomainsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CustomDomainsApi()

    def tearDown(self) -> None:
        pass

    def test_create_custom_domain(self) -> None:
        """Test case for create_custom_domain

        Create custom domain
        """
        pass

    def test_list_custom_domains(self) -> None:
        """Test case for list_custom_domains

        List custom domains
        """
        pass


if __name__ == '__main__':
    unittest.main()
