# coding: utf-8

"""
    GetHook API

    Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from gethook.api.events_api import EventsApi


class TestEventsApi(unittest.TestCase):
    """EventsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EventsApi()

    def tearDown(self) -> None:
        pass

    def test_get_event(self) -> None:
        """Test case for get_event

        Get inbound event
        """
        pass

    def test_list_events(self) -> None:
        """Test case for list_events

        List inbound events
        """
        pass

    def test_replay_event(self) -> None:
        """Test case for replay_event

        Replay inbound event
        """
        pass


if __name__ == '__main__':
    unittest.main()
