# coding: utf-8

"""
    GetHook API

    Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AttemptOutcome(str, Enum):
    """
    AttemptOutcome
    """

    """
    allowed enum values
    """
    OutcomePending = 'pending'
    OutcomeSuccess = 'success'
    OutcomeTimeout = 'timeout'
    OutcomeNetworkError = 'network_error'
    OutcomeHTTP4xx = 'http_4xx'
    OutcomeHTTP5xx = 'http_5xx'
    OutcomeCancelled = 'cancelled'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AttemptOutcome from a JSON string"""
        return cls(json.loads(json_str))


