# coding: utf-8

"""
    GetHook API

    Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class BrandSettings(BaseModel):
    """
    BrandSettings
    """ # noqa: E501
    account_id: StrictStr
    company_name: Optional[StrictStr] = None
    created_at: StrictStr
    docs_title: Optional[StrictStr] = None
    id: StrictStr
    logo_url: Optional[StrictStr] = None
    primary_color: Optional[StrictStr] = None
    support_email: Optional[StrictStr] = None
    updated_at: StrictStr
    __properties: ClassVar[List[str]] = ["account_id", "company_name", "created_at", "docs_title", "id", "logo_url", "primary_color", "support_email", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BrandSettings from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BrandSettings from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "account_id": obj.get("account_id"),
            "company_name": obj.get("company_name"),
            "created_at": obj.get("created_at"),
            "docs_title": obj.get("docs_title"),
            "id": obj.get("id"),
            "logo_url": obj.get("logo_url"),
            "primary_color": obj.get("primary_color"),
            "support_email": obj.get("support_email"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


