# coding: utf-8

"""
    GetHook API

    Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from gethook.models.attempt_outcome import AttemptOutcome
from typing import Optional, Set
from typing_extensions import Self

class DeliveryAttempt(BaseModel):
    """
    DeliveryAttempt
    """ # noqa: E501
    attempt_number: StrictInt
    destination_id: StrictStr
    error_message: Optional[StrictStr] = None
    event_id: StrictStr
    finished_at: Optional[StrictStr] = None
    id: StrictStr
    latency_ms: Optional[StrictInt] = None
    outcome: AttemptOutcome
    response_body: Optional[StrictStr] = None
    response_status: Optional[StrictInt] = None
    started_at: StrictStr
    __properties: ClassVar[List[str]] = ["attempt_number", "destination_id", "error_message", "event_id", "finished_at", "id", "latency_ms", "outcome", "response_body", "response_status", "started_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeliveryAttempt from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeliveryAttempt from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attempt_number": obj.get("attempt_number"),
            "destination_id": obj.get("destination_id"),
            "error_message": obj.get("error_message"),
            "event_id": obj.get("event_id"),
            "finished_at": obj.get("finished_at"),
            "id": obj.get("id"),
            "latency_ms": obj.get("latency_ms"),
            "outcome": obj.get("outcome"),
            "response_body": obj.get("response_body"),
            "response_status": obj.get("response_status"),
            "started_at": obj.get("started_at")
        })
        return _obj


