# coding: utf-8

"""
    GetHook API

    Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class DestinationPreset(BaseModel):
    """
    DestinationPreset
    """ # noqa: E501
    auth_header: Optional[StrictStr] = Field(default=None, description="for api_key type")
    auth_label: Optional[StrictStr] = Field(default=None, description="e.g. \"Bot Token\", \"API Key\"")
    auth_type: Optional[StrictStr] = Field(default=None, description="\"none\", \"bearer\", \"api_key\"")
    category: Optional[StrictStr] = None
    color: Optional[StrictStr] = None
    description: Optional[StrictStr] = None
    docs_url: Optional[StrictStr] = None
    extra_headers: Optional[Dict[str, StrictStr]] = None
    id: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    url_hint: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["auth_header", "auth_label", "auth_type", "category", "color", "description", "docs_url", "extra_headers", "id", "name", "url_hint"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DestinationPreset from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DestinationPreset from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "auth_header": obj.get("auth_header"),
            "auth_label": obj.get("auth_label"),
            "auth_type": obj.get("auth_type"),
            "category": obj.get("category"),
            "color": obj.get("color"),
            "description": obj.get("description"),
            "docs_url": obj.get("docs_url"),
            "extra_headers": obj.get("extra_headers"),
            "id": obj.get("id"),
            "name": obj.get("name"),
            "url_hint": obj.get("url_hint")
        })
        return _obj


