# coding: utf-8

"""
    GetHook API

    Webhook Reliability Gateway — accept inbound webhooks, persist them durably, forward to destinations, retry failures, and replay past events.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from gethook.models.direction import Direction
from gethook.models.event_status import EventStatus
from typing import Optional, Set
from typing_extensions import Self

class Event(BaseModel):
    """
    Event
    """ # noqa: E501
    account_id: StrictStr
    attempts_count: StrictInt
    body: StrictStr
    created_at: StrictStr
    created_by: Optional[StrictStr] = None
    direction: Direction
    event_type: Optional[StrictStr] = None
    external_event_id: Optional[StrictStr] = None
    final_state: Optional[StrictStr] = None
    headers: Dict[str, Any]
    id: StrictStr
    next_attempt_at: Optional[StrictStr] = None
    payload_hash: Optional[StrictStr] = None
    received_at: StrictStr
    source_id: Optional[StrictStr] = None
    status: EventStatus
    __properties: ClassVar[List[str]] = ["account_id", "attempts_count", "body", "created_at", "created_by", "direction", "event_type", "external_event_id", "final_state", "headers", "id", "next_attempt_at", "payload_hash", "received_at", "source_id", "status"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Event from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Event from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "account_id": obj.get("account_id"),
            "attempts_count": obj.get("attempts_count"),
            "body": obj.get("body"),
            "created_at": obj.get("created_at"),
            "created_by": obj.get("created_by"),
            "direction": obj.get("direction"),
            "event_type": obj.get("event_type"),
            "external_event_id": obj.get("external_event_id"),
            "final_state": obj.get("final_state"),
            "headers": obj.get("headers"),
            "id": obj.get("id"),
            "next_attempt_at": obj.get("next_attempt_at"),
            "payload_hash": obj.get("payload_hash"),
            "received_at": obj.get("received_at"),
            "source_id": obj.get("source_id"),
            "status": obj.get("status")
        })
        return _obj


